config/routes.rb
Szkolenia::Application.routes.draw do

  resources :zawod, path: "szkoly_dla_doroslych", :except => [:new, :create, :edit, :update, :destroy]

  root to: redirect("/baza/trainings")

  resources :trainings, :except => [:noweszkolenie, :nowestudia, :new, :create, :edit, :update, :destroy] do
    collection do
      get :szkolenia, :studia_podyplomowe, :studia_wyzsze, :instytucje_szkoleniowe
    end
  end

end

app/models/training.rb
# coding: utf-8
class Training < ActiveRecord::Base
  resourcify
  belongs_to :location
  belongs_to :category
  belongs_to :organizer

  has_and_belongs_to_many :trainers

  accepts_nested_attributes_for :organizer

  default_scope {
    order(id: :desc)
  }

  # validates_presence_of :trainers, message: "Nie wybrano trenera!", unless: :studies
  validates_presence_of :organizer, message: "Nie wybrano organizatora!"
  validates_presence_of :category, message: "Nie wybrano kategorii!"
  validates_presence_of :location, message: "Nie wybrano lokalizacji!"
  #validate :has_trainers?

  def has_trainers?
    errors.add(:trainers, 'nie wybrano żadnych trenerów!') if self.trainers.blank? and self.szkolenie?
  end

  #validate :_type_valid, :_category_valid
  
  def szkolenie?
  	!studies  	
  end

  def studia?
  	studies and !postgrad  	
  end

  def podyplomowe?
  	@studies and @postgrad
  end

 #  def _category_valid
 #  	@studies==@category.studies
 #  end

 #  def _type_valid
 #  	(studies and postgrad) or (studies and !postgrad) or not (!studies and postgrad)
 #  	# tudzież (studies && postgrad) || (studies && !postgrad) || !(!studies && postgrad)
 #  	# czyli dopuszczalne nastepujące typy: 
 #  	# *studia podyplomowe
 #  	# *studia normalne
 #  	# *szkolenia
 #  	# nie dopuszczamy innych, szkolenia [czyli nie-studia] podyplomowe będą błędne
 #  	# formularze nie powinny na to pozwolić, ale ktoś może przy nich manipulować, takze tak na wszelki wypadek:)
	# # prawdopodobnie możnaby było się ograniczyć do `!(!studies && postgrad)`
 #  end
end

app/controllers/trainings_controller.rb
# coding: utf-8
class TrainingsController < ApplicationController
  before_action :set_training, only: [:show, :edit, :update, :destroy, :toggle_active]
#  before_action :authorize
  # before_action :check_admin, only: [:noweszkolenie, :nowestudia, :create, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json

  def index
    @trainings = Training.all
  end

  def toggle_active
    if @training.active?
      @training.active=false
      puts 'x'
    else
      @training.active=true
      puts 'y'
    end
    render :nothing => true
  end

  def studia_wyzsze
  	conditions= {studies: true, postgrad: false}
  	prepare_conditions(conditions) if params[:commit]
  	unless params[:query].blank?
  		namelike = "%#{params[:query]}%"
  		@trainings = Training.where(conditions).where("name LIKE ?", namelike)
  	else
  		@trainings = Training.where(conditions)
  	end
  end

  def studia_podyplomowe
  	conditions= {studies: true, postgrad: true}
  	prepare_conditions(conditions) if params[:commit]
  	unless params[:query].blank?
  		namelike = "%#{params[:query]}%"
  		@trainings = Training.where(conditions).where("name LIKE ?", namelike)
  	else
  		@trainings = Training.where(conditions)
  	end
  end

  def szkolenia
  	conditions = {studies: false}
  	prepare_conditions(conditions) if params[:commit]
  	unless params[:query].blank?
  		namelike = "%#{params[:query]}%"
  		@trainings = Training.where(conditions).where("name LIKE ?", namelike)
  	else
  		@trainings = Training.where(conditions)
  	end
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    if @training.studies
      puts ">>studia"
      render "show_studia"
    else
      puts ">>szkolenia"
      render "show_szkolenie"
    end
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @training.build_organizer
  end


  alias_method :noweszkolenie, :new

  alias_method :nowestudia, :new

  # GET /trainings/1/edit
  def edit
    if @training.studies
      puts ">>studia"
      render :edit_studia
    else
      puts ">>szkolenia"
      render :edit_szkolenie
    end
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)
    @training.location=Location.find(training_params[:location_id].to_i) unless training_params[:location_id].blank?
    @training.category=Category.find(training_params[:category_id].to_i) unless training_params[:category_id].blank?
    @training.organizer=Organizer.find(training_params[:organizer_id].to_i) unless training_params[:organizer_id].blank?
    p training_params
    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Zapisano pomyślnie' }
      else
        format.html do
          if @training.studies
            render action: "nowestudia"
          else
            render action: "noweszkolenie"
          end
        end
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      @training.location=Location.find(training_params[:location_id].to_i) unless training_params[:location_id].blank?
      @training.category=Category.find(training_params[:category_id].to_i) unless training_params[:category_id].blank?
      @training.organizer=Organizer.find(training_params[:organizer_id].to_i) unless training_params[:organizer_id].blank?
      @training.trainers=Trainer.find(training_params[:trainer_ids][1..-1].map {|trainer_id| trainer_id.to_i}) unless training_params[:trainer_ids].blank?
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Zaktualizowano pomyślnie' }
      else
        format.html do
          if @training.studies
            render action: 'edit_studia'
          else
            render action: 'edit_szkolenie'
          end
        end
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    if @training.szkolenie?
      red_url=szkolenia_trainings_url
    elsif @training.studia?
      red_url=studia_wyzsze_trainings_url
    else
      red_url=studia_podyplomowe_trainings_url
    end
    @training.destroy
    respond_to do |format|
      format.html { redirect_to red_url }
      format.json { head :no_content }
    end
  end

  def instytucje_szkoleniowe
  end

  private

    def prepare_conditions(conditions)
      conditions[:location] = Location.find(params[:location_id].to_i) unless params[:location_id].blank? or params[:location_id] == "18"
      conditions[:category] = Category.find(params[:category_id].to_i) unless params[:category_id].blank?
      conditions[:organizer] = Organizer.find(params[:organizer_id].to_i) unless params[:organizer_id].blank?
      conditions[:elearning] = true if params[:elearning]=='1'
      conditions[:paid] = false if params[:free]=='1'
      puts ">> conditions"
      p conditions
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(
        :name,
        :info,
        :moreinfo,
        :target,
        :methods,
        :groupsize,
        :trainer_info,
        :studies,
        :postgrad,
        :elearning,
        :paid,
        :costs,
        :costs_info,
        :term,
        :term_info,
        :term_notes,
        :term_contact,
        :begin_date,
        :end_date,
        :address,
        :organizer_id,
        :location_id,
        :category_id,
        organizer_attributes: [
          :name,
          :address,
          :contact,
          :link,
          :college],
        trainer_ids: [] )
    end

    def check_admin
      raise ActionController::RoutingError.new('Not Found') unless current_user.admin?
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_studia_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= "#{@training.errors.count} błędów" %> przeszkodziło w zachowaniu danych</h2>

      <ul>
      <% @training.errors.messages.each do |msg| %>
        <li><%= msg[1][0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="<%= @training.postgrad ? 'studiapform' : 'studiawform' %>">
  <div class="field">
    <%= f.label :name, "Nazwa studiów" %>
    <%= f.text_field :name, size: 80, maxlength: 255 %>
  </div>

  <%= field_set_tag "Podstawowe informacje o studiach", id:"info" do %>
    <div class="field">
      <%= f.label :info, "Opis studiów" %>
      <%= f.text_area :info %>
    </div>
    <div class="field">
      <%= f.label :methods, "Specjalności" %>
      <%= f.text_area :methods %>
    </div>
  <% end %>

  <%= field_set_tag "Organizacja studiów", id:"organizacja_s" do %>
    <div class="field">
      <%= f.text_area :moreinfo %>
    </div>
  <% end %>

  <%= field_set_tag "Lokalizacja", id: "lokalizacja" do %>
    <div class="field">
      <%= f.label :address, "Adres wydziału" %>
      <%= f.text_area :address %>
    </div>
  <% end %>

  <%= field_set_tag "Organizator", id:"uczelnia" do %>
    <div class="field hint--info hint--bottom" data-hint="Wyświetlani są tylko organizatorzy oznaczeni jako Uczelnia">
      <%= f.label :organizer_id %>
      <%= f.select(:organizer_id, Organizer.order(:name).map { |org| [org.name, org.id] }, {include_blank: "Wybierz organizatora"}) %>
    </div>
  <% if f.object.new_record? %>
    <p style="text-align: center">lub wpisz nowego</p>
    <%= f.fields_for :organizer do |org| %>
      <div class="field">
        <%= org.label :name, "Nazwa organizatora/uczelni" %>
        <%= org.text_field :name, size: 80, maxlength: 255  %>
      </div>
      <div class="field">
        <%= org.label :address, "Adres organizatora/uczelni" %>
        <%= org.text_area :address %>
      </div>
      <div class="field">
        <%= org.label :contact, "Dane kontaktowe" %>
        <%= org.text_area :contact %>
      </div>
      <div class="field">
        <%= org.label :link, "Adres WWW organizatora/uczelni" %>
        <%= org.text_field :link, size: 80, maxlength: 255  %>
      </div>
      <%= org.hidden_field :college, value: 1 %>
    <% end %>
  <% end %>
  <% end %>

  <%= field_set_tag "Koszty", id: "koszty" do %>
    <div class="field">
      <%= f.label :paid %>
      <%= f.check_box :paid %>
    </div>
    <div class="field">
      <%= f.label :costs, "Koszt studiów" %>
      <%= f.text_area :costs, size: 80, maxlength: 255 %>
    </div>
    <div class="field">
      <%= f.label :costs_info, "Dodatkowe informacje na temat kosztów" %>
      <%= f.text_area :costs_info %>
    </div>
  <% end %>
  <%= field_set_tag "Forma studiów", id: "postgrad" do %>
    <div class="field">
      <%= f.label :postgrad, "Podyplomowe" %>
      <%= f.check_box :postgrad %>
    </div>
  <% end %>
  <%= field_set_tag "Rejon i kategoria", id: "loccat" do %>
    <div class="field">
      <%= f.label :location_id %>
      <%= f.select(:location_id, Location.all.map {|location| [location.name, location.id]}, {include_blank: "Wybierz lokalizację"}) %>
    </div>
    <div class="field">
      <%= f.label :category_id %>
      <%= f.select(:category_id, Category.where(studies: true).map { |cat| [cat.name,cat.id]}, {include_blank: "Wybierz kategorię"}) %>
    </div>
  <% end %>
  <%= f.hidden_field :studies, value: 1 %>
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
</div>
<% end %>

app/views/trainings/_studia_search_form.html.erb
	<div class="field">
	    <%= label_tag :query, "Słowo kluczowe" %>
	    <%= text_field_tag :query, params[:query] %>
	</div>
	<div class="field">
	    <%= label_tag :location_id, "Lokalizacja" %>
		<%= select_tag(:location_id, options_from_collection_for_select(Location.all, :id, :name, params[:location_id]), prompt: "Wybierz lokalizację") %>
	</div>
	<div class="field">
	    <%= label_tag :training_category_id, "Kategoria" %>
		<%= select_tag(:category_id, options_from_collection_for_select(Category.where(studies: true), :id, :name, params[:category_id]), prompt: "Wybierz kategorię") %>
	</div>
	<div class="field">
      <%= label_tag :free, "Tylko bezpłatne" %>
      <%= check_box_tag :free, '1', params[:free]=='1'?true:false %>
    </div>
    <%= hidden_field_tag :organizer_id, params[:organizer_id] %>
	<%= submit_tag "Wyszukaj" %> 

app/views/trainings/_studia_table.html.erb
<thead>
    <tr>
      <th>Kierunek studiów</th>
      <th>Uczelnia</th>
      <th>E-learning</th>
      <th>Płatne</th>
      <th>Lokalizacja (powiat)</th>
      <th>Kategoria (dziedzina)</th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= link_to training.name, training %></td>
        <td><%= training.organizer.name %></td>
        <td><%= training.elearning ? "Tak" : "Nie" %></td>
        <td><%= training.paid ? "Tak" : "Nie" %></td>
        <td><%= training.location.name %></td>
        <td><%= sanitize training.category.name.gsub("/", "/&#8203;") %></td>
      </tr>
    <% end %>
  </tbody>

app/views/trainings/edit_szkolenie.html.erb
<h1>Edycja szkolenia</h1>

<%= render 'szkolenie_form' %>

app/views/trainings/instytucje_szkoleniowe.html.erb
<div class="instytucje">
	<%= link_to "Rejestr Instytucji Szkoleniowych", "http://ris.praca.gov.pl/ris/index.ftl" %>
	<%= link_to "System Informacji Oświatowej", "http://www.cie.men.gov.pl/index.php/wyszukiwarka.html" %>
</div>

app/views/trainings/nowestudia.html.erb
<h1>Nowe studia</h1>

<%= render 'studia_form' %>

app/views/trainings/podyplomowe.html.erb
<h1>Lista studiów podyplomowych</h1>

<table>
  <thead>
    <tr>
      <th>Kierunek studiów</th>
      <th>Uczelnia</th>
      <th>E-learning</th>
      <th>Płatne</th>
      <th>Lokalizacja (powiat)</th>
      <th>Kategoria (dziedzina)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= link_to training.name, training %></td>
        <td><%= training.organizer.name %></td>
        <td><%= training.elearning ? "Tak" : "Nie" %></td>
        <td><%= training.paid ? "Tak" : "Nie" %></td>
        <td><%= training.location.name %></td>
        <td><%= training.category.name %></td>
        <td><%= link_to 'Edytuj', edit_training_path(training) %></td>
        <td><%= link_to 'Usuń', training, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowe studia' , nowestudia_trainings_path %>

app/views/trainings/show_podyplomowe.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazwa:</strong>
  <%= @training.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @training.info %>
</p>

<p>
  <strong>Info2:</strong>
  <%= @training.moreinfo %>
</p>

<p>
  <strong>Studia:</strong>
  <%= @training.studies %>
</p>

<p>
  <strong>Podyplomowe:</strong>
  <%= @training.postgrad %>
</p>

<p>
  <strong>E-learning:</strong>
  <%= @training.elearning %>
</p>

<p>
  <strong>Płatne:</strong>
  <%= @training.paid %>
</p>

<p>
  <strong>Koszty:</strong>
  <%= @training.costs %>
</p>

<p>
  <strong>Termin:</strong>
  <%= @training.term %>
</p>

<p>
  <strong>Adres:</strong>
  <%= @training.address %>
</p>

<p>
  <strong>Organizator:</strong>
  <%= @training.organizer %>
</p>

<p>
  <strong>Lokalizacja (powiat):</strong>
  <%= @training.location.name %>
</p>

<p>
  <strong>Kategoria: (dziedzina)</strong>
  <%= @training.category.name %>
</p>

<%= link_to 'Edycja', edit_training_path(@training) %> |
<%= link_to 'Wstecz', trainings_path %>

app/views/trainings/show_szkolenie.html.erb
<p id="notice"><%= notice %></p>

<h2><%=link_to @training.category.name, szkolenia_trainings_path(category_id: @training.category.id, commit: true) %>/<%= @training.name %></h2>

<div id="map1"></div>

<div class="szkolenie">
  <ul class="tabs">
    <li><a href="#program">Program</a></li>
    <li><a href="#lokalizacja">Lokalizacja</a></li>
    <li><a href="#organizator">Organizator</a></li>
    <li><a href="#koszty">Koszty</a></li>
    <li><a href="#termin">Termin</a></li>
  </ul>

  <div id="program">
    <p>
      <strong>Cel szkolenia:</strong>
      <%= simple_format  @training.target %>
    </p>
    <p>
      <strong>Forma szkolenia:</strong>
      <%= @training.elearning ? "E-learning" : "Stacjonarne" %>
    </p>
    <p>
      <strong>Program szkolenia:</strong>
      <%= simple_format @training.info %>
    </p>
  <% unless @training.trainers.empty? %>
    <p>
    <strong>Trener/-rzy:</strong>
      <ul>
      <% @training.trainers.each do |trainer| %>
        <li><%= link_to trainer.name, trainer %></li>
      <% end %>
      </ul>
    </p>
  <% else %>
    <p>
      <strong>Informacje o kadrze trenerskiej:</strong>
      <%= simple_format @training.trainer_info %>
    </p>
  <% end %>
    <p>
      <strong>Metody szkolenia:</strong>
      <%= simple_format @training.methods %>
    </p>
    <p>
      <strong>Wielkość grupy:</strong>
      <%= simple_format @training.groupsize %>
    </p>
    <p>
      <strong>Uwagi:</strong>
      <%= simple_format @training.moreinfo %>
    </p>
  </div>


  <div id="lokalizacja">
    <div id="mapa">
    <%= @training.address %>
    </div>
  </div>

  <div id="organizator">
    <p>
      <strong>Nazwa organizatora:</strong>
      <% unless @training.organizer.link.blank? %>
      <a href="<%= @training.organizer.link %>"><%= @training.organizer.name %></a>
      <% else %>
      <%= @training.organizer.name %>
      <% end %>
    </p>
    <p>
      <strong>Adres organizatora:</strong>
      <%= simple_format @training.organizer.address %>
    </p>
    <p>
      <strong>Kontakt:</strong>
      <%= simple_format @training.organizer.contact %>
    </p>
  </div>

  <div id="koszty">
  <% unless @training.paid %>
    <p>Szkolenie jest bezpłatne</p>
  <% else %>
    <p>
      <strong>Koszty uczestnictwa jednej osoby:</strong>
      <%= simple_format @training.costs %>
    </p>
    <p>
      <strong>Dodatkowe informacje na temat kosztów:</strong>
      <%= simple_format @training.costs_info %>
    </p>
  <% end %>
  </div>

  <div id="termin">
    <p>
      <strong>Termin zgłoszenia:</strong>
      <%= @training.term %>
    </p>
    <p>
      <strong>Czas trwania szkolenia:</strong>
      <%= simple_format @training.term_info %>
    </p>
  <% if @training.term_contact and @training.term_contact!="" %>
    <p>
      <strong>Kontakt w sprawie szkolenia:</strong>
      <%= simple_format @training.term_contact %>
    </p>
  <% end %>
  <% if @training.begin_date %>
    <p>
      <strong>Data rozpoczęcia:</strong>
      <%= @training.begin_date %>
    </p>
  <% else %>
    <p>
      <strong>Data rozpoczęcia:</strong>
      <%= simple_format @training.term_notes %>
    </p>
  <% end %>
  <% if @training.end_date %>
    <p>
      <strong>Data zakończenia:</strong>
      <%= @training.end_date %>
    </p>
  <% end %>
  </div>
</div>

<%# if current_user.admin? %>
  <%#= link_to 'Edycja', edit_training_path(@training), class: "szkolenie_link_block" %>
<%# end %>

app/views/trainings/studia.html.erb
<h1>Lista studiów</h1>

<table>
  <thead>
    <tr>
      <th>Kierunek studiów</th>
      <th>Uczelnia</th>
      <th>E-learning</th>
      <th>Płatne</th>
      <th>Lokalizacja (powiat)</th>
      <th>Kategoria (dziedzina)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= link_to training.name, training %></td>
        <td><%= training.organizer.name %></td>
        <td><%= training.elearning ? "Tak" : "Nie" %></td>
        <td><%= training.paid ? "Tak" : "Nie" %></td>
        <td><%= training.location.name %></td>
        <td><%= training.category.name %></td>
        <td><%= link_to 'Edytuj', edit_training_path(training) %></td>
        <td><%= link_to 'Usuń', training, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowe studia' , nowestudia_trainings_path %>

app/views/trainings/studia_podyplomowe.html.erb
<div class="search studiapodyplomowe">
<%= form_tag studia_podyplomowe_trainings_path, method: "get" do %>
<div id="studiapform">
<%= field_set_tag "Studia podyplomowe" do %>
 <%= render "studia_search_form" %>
<% end %>
</div>
<% end %>
</div>
<% if params[:commit] %>
<% unless @trainings.empty? and params[:commit] %>
<table class="studiapodyplomowe">
   <%= render "studia_table" %>
</table>
<% else %>
<p style="text-align: center; border: dashed 4px red; padding: 20px; width: 800px; margin:  20px auto 20px auto; background: lavenderblush; font-size: large;">Nie znaleziono żadnych pozycji. Przejdź na inną zakładkę albo wybierz inne kryterium wyszukiwania.</p>
<% end %>
<% end %>

app/views/trainings/studia_wyzsze.html.erb
<div class="search studiawyzsze">
<%= form_tag studia_wyzsze_trainings_path, method: "get" do %>
<div id="studiawform">
<%= field_set_tag "Studia wyższe", id: "search" do %>
 <%= render "studia_search_form" %>
 <% end %>
 </div>
<% end %>
</div>
<% if params[:commit] %>
<% unless @trainings.empty? and params[:commit] %>
<table class="studiawyzsze">
   <%= render "studia_table" %>
</table>
<% else %>
<p style="text-align: center; border: dashed 4px red; padding: 20px; width: 800px; margin:  20px auto 20px auto; background: lavenderblush; font-size: large;">Nie znaleziono żadnych pozycji. Przejdź na inną zakładkę albo wybierz inne kryterium wyszukiwania.</p>
<% end %>
<% end %>

app/views/trainings/szkolenia.html.erb
<div class="search">
<%= form_tag szkolenia_trainings_path, method: "get" do %>
<div id="szkolenieform">
<%= field_set_tag "Szkolenia" do %>
	<div class="field">
	    <%= label_tag :query, "Słowo kluczowe" %>
	    <%= text_field_tag :query, params[:query] %>
	</div>
	<div class="field">
	  <%= label_tag :location_id, "Lokalizacja" %>
		<%= select_tag(:location_id, options_from_collection_for_select(Location.all, :id, :name, params[:location_id]), prompt: "Wybierz lokalizację") %>
	</div>
	<div class="field">
	  <%= label_tag :training_category_id, "Kategoria" %>
		<%= select_tag(:category_id, options_from_collection_for_select(Category.where(studies: false), :id, :name, params[:category_id]), prompt: "Wybierz kategorię") %>
	</div>
	<div class="field">
    <%= label_tag :free, "Tylko bezpłatne" %>
    <%= check_box_tag :free, '1', params[:free]=='1'?true:false %>
  </div>
  <div class="field">
    <%= label_tag :elearning, "Tylko e-learning" %>
    <%= check_box_tag :elearning, '1', params[:elearning]=='1'?true:false %>
  </div>
  <%= hidden_field_tag :organizer_id, params[:organizer_id] %>
	<%= submit_tag "Wyszukaj" %>
<% end %>
</div>
<% end %>
</div>
<% if params[:commit] %>
<% unless @trainings.empty? and params[:commit] %>
<table class="szkolenia">
  <thead>
    <tr>
      <th>Nazwa szkolenia</th>
      <th>Data rozpoczęcia</th>
      <th>Czas trwania</th>
      <th>Lokalizacja (powiat)</th>
      <th>Płatne</th>
      <% if false %><th>Aktywne</th><% end %>
	<% if false %>
	<% if current_user.admin? %>
      <th></th>
	<% end %>
	<% end %>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= link_to training.name, training %></td>
        <td>
        <% if training.begin_date %>
          <%= training.begin_date %>
        <% else %>
          <%= training.term_notes %>
        <% end %></td>
        <td><%= training.term_info %></td>
        <td><%= training.location.name %></td>
        <td><%= training.paid ? "Tak" : "Nie" %></td>
        <% if false %><td class="nolink"><%= check_box_tag 'active'+training.id.to_s, training.id, training.active, :class => 'active' %><label for="<%= "active"+training.id.to_s %>" ><%= training.active ? "Aktywne" : "Nieaktywne" %></label></td><% end %>
    <% if false %><% if current_user.admin? %>
        <td class="nolink"><%= link_to 'Edytuj', edit_training_path(training) %> | <%= link_to 'Usuń', training, method: :delete, data: { confirm: 'Jesteś pewien?' } %></td>
    <% end %><% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p style="text-align: center; border: dashed 4px red; padding: 20px; width: 800px; margin:  20px auto 20px auto; background: lavenderblush; font-size: large;">Nie znaleziono żadnych pozycji. Przejdź na inną zakładkę albo wybierz inne kryterium wyszukiwania.</p>
<% end %>
<% end %>