config/routes.rb
Szkolenia::Application.routes.draw do

  resources :zawod, path: "szkoly_dla_doroslych", :except => [:new, :create, :edit, :update, :destroy]

  root to: redirect("/baza/trainings")

  resources :trainings, :except => [:noweszkolenie, :nowestudia, :new, :create, :edit, :update, :destroy] do
    collection do
      get :szkolenia, :studia_podyplomowe, :studia_wyzsze, :instytucje_szkoleniowe
    end
  end

end

app/views/layouts/_ga.html.erb
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-21115418-6'], ['_trackPageview']);
	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Baza danych o usługach edukacyjnych</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false" %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= render partial: "layouts/ga" if Rails.env.production? %>

	</head>
	<body>
		<% if params[:action]=="index" && params[:controller]=="trainings"%>
		<div id="nav" style="top: 30%; height:200px;">
		<% else %>
		<div id="nav">
		<% end %>
			<h2>
		<% if (params[:action]=="index" && params[:controller]=="trainings") %><%# || !signed_in? %>
			Baza danych o usługach edukacyjnych
		<% else %>
			<%= link_to "Baza danych o usługach edukacyjnych", trainings_path %>
		<% end %>
			</h2>
		<%# if signed_in? %>
			<ul>
				<li><%= link_to 'Szkolenia/kursy', szkolenia_trainings_path, class: "przycisk szkolenie_link" %></li>
				<li><%= link_to 'Studia wyższe', studia_wyzsze_trainings_path, class: "przycisk studiaw_link" %></li>
				<li><%= link_to 'Studia podyplomowe', studia_podyplomowe_trainings_path, class: "przycisk studiap_link" %></li>
				<li><%= link_to 'Szkoły dla dorosłych', zawod_index_path, class: "przycisk ustawiczne_link" %></li>
			</ul>
			<% if params[:action]=="index" && params[:controller]=="trainings"%>
				<p>
					<%= link_to "Wykaz szkół i instytucji szkoleniowych", instytucje_szkoleniowe_trainings_path, class: "przycisk instytucje_link" %>
				</p>
			<% end %>
		<%# end %>
		</div>
		<% if params[:action]=="index" && controller.controller_name=="trainings" %>
		<div id="content" style="top: 60%">
		<% else %>
		<div id="content">
		<% end %>
			<%= yield %>
			<img id="footer" src="http://azymut.up.podlasie.pl/templates/jf_texturia/images/logo1.png">
			<% if !signed_in? %><a style="text-align: center; margin-right: auto; margin-left: auto; display: block;" href="http://www.azymut.up.podlasie.pl/">Powrót na stronę główną projektu</a><% end %>
		</div>
		<% if signed_in? %>
		<div id="nav2">
			<ul>
			<% if current_user.admin? %>
				<li><%= link_to 'Nowe szkolenie', noweszkolenie_trainings_path, class: "przycisk szkolenie_link" %></li>
				<li><%= link_to 'Nowe studia', nowestudia_trainings_path, class: "przycisk studiaw_link" %></li>
				<li><%= link_to 'Nowy zawód', new_zawod_path, class: "przycisk ustawiczne_link" %></li>
				<li><%= link_to 'Organizatorzy', organizers_path, class: "sbutton" %></li>
				<li><%= link_to 'Trenerzy', trainers_path, class: "sbutton" %></li>
			<% end %>
			<% if current_user.admin? or current_user.doradca? %>
				<li><%= link_to 'Użytkownicy', users_path, class: "sbutton" %></li>
			<% end %>
			<% if current_user.admin? %>
				<li><%= link_to 'Nowy organizator', new_organizer_path, class: "sbutton" %></li>
				<li><%= link_to 'Nowy trener', new_trainer_path, class: "sbutton" %></li>
			<% end %>
			<% if current_user.admin? or current_user.doradca? %>
				<li><%= link_to 'Nowy użytkownik', new_user_path, class: "sbutton" %></li>
			<% end %>
			</ul>
			<p> Zalogowany jako <%=current_user.name%>	<%= link_to "Wyloguj", sign_out_path, :method => :delete %> | <a href="http://www.azymut.up.podlasie.pl/">Powrót na stronę główną projektu</a></p>
		</div>
		<% end %>
	</body>
</html>